# Generated by Django 6.0.3 on 2026-03-15 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_settings', '0004_alter_appoption_category'),
        ('clients', '0006_treatment_balance_treatment_session_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(blank=True, limit_choices_to={'category': 'payment_method', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_method', to='app_settings.appoption')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.treatment')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
