# Generated by Django 6.0.3 on 2026-03-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permission_profile_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
