# Generated by Django 6.0.3 on 2026-03-16 12:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_settings', '0005_alter_appoption_category'),
        ('clients', '0007_treatment_total_remaining_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('client_full_name', models.CharField(editable=False, max_length=255)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('type_and_site', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_sessions', models.PositiveIntegerField()),
                ('session_rhythm_text', models.CharField(editable=False, max_length=150)),
                ('invoice_type_text', models.CharField(editable=False, max_length=150)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clients.client')),
                ('invoice_type', models.ForeignKey(limit_choices_to={'category': 'invoice_type', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_type', to='app_settings.appoption')),
                ('session_rhythm', models.ForeignKey(limit_choices_to={'category': 'session_rhythm', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_session_rhythm', to='app_settings.appoption')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
