# Generated by Django 6.0.3 on 2026-03-07 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('cin', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='clients/profile_photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dossier_type', models.ForeignKey(blank=True, limit_choices_to={'category': 'dossier_type', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_dossier_type', to='app_settings.appoption')),
                ('gender', models.ForeignKey(blank=True, limit_choices_to={'category': 'gender', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_gender', to='app_settings.appoption')),
                ('marital_status', models.ForeignKey(blank=True, limit_choices_to={'category': 'marital_status', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_marital_status', to='app_settings.appoption')),
                ('social_security', models.ForeignKey(blank=True, limit_choices_to={'category': 'social_security', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_social_security', to='app_settings.appoption')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('treating_doctor', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('prescribed_sessions', models.PositiveIntegerField(default=0)),
                ('completed_sessions', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='clients.client')),
                ('diagnosis_site', models.ForeignKey(blank=True, limit_choices_to={'category': 'diagnosis_site', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_diagnosis_site', to='app_settings.appoption')),
                ('diagnosis_type', models.ForeignKey(blank=True, limit_choices_to={'category': 'diagnosis_type', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_diagnosis_type', to='app_settings.appoption')),
                ('session_rhythm', models.ForeignKey(blank=True, limit_choices_to={'category': 'session_rhythm', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_session_rhythm', to='app_settings.appoption')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
