# Generated by Django 6.0.3 on 2026-03-08 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
        ('clients', '0002_alter_client_file_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='diagnosis_site',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='diagnosis_type',
        ),
        migrations.AddField(
            model_name='treatment',
            name='type_and_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='session_rhythm',
            field=models.ForeignKey(limit_choices_to={'category': 'session_rhythm', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_session_rhythm', to='app_settings.appoption'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='start_date',
            field=models.DateField(),
        ),
    ]
