# Generated by Django 6.0.3 on 2026-03-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_treatment_diagnosis_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='type_and_site',
            field=models.CharField(max_length=255),
        ),
    ]
