# Generated by Django 6.0.3 on 2026-03-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_treatment_type_and_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='completed_sessions',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
