# Generated by Django 6.0.3 on 2026-03-16 05:32

from decimal import Decimal
from django.db import migrations, models


def backfill_total_remaining_amount(apps, schema_editor):
    Treatment = apps.get_model("clients", "Treatment")
    for treatment in Treatment.objects.all():
        paid_sessions_count = treatment.sessions.filter(
            payment_status__category="payment_status",
            payment_status__code__in=["paid", "payed"],
            payment_status__is_active=True,
        ).count()
        paid_amount = (treatment.session_price or Decimal("0")) * Decimal(paid_sessions_count)
        remaining = (treatment.total_price or Decimal("0")) - (
            paid_amount + (treatment.balance or Decimal("0"))
        )
        treatment.total_remaining_amount = remaining if remaining > 0 else Decimal("0")
        treatment.save(update_fields=["total_remaining_amount"])


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_treatment_balance_treatment_session_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='total_remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.RunPython(backfill_total_remaining_amount, migrations.RunPython.noop),
    ]
