# Generated by Django 6.0.3 on 2026-03-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('gender', 'Gender'), ('dossier_type', 'Dossier Type'), ('marital_status', 'Marital Status'), ('social_security', 'Social Security'), ('diagnosis_type', 'Diagnosis Type'), ('diagnosis_site', 'Diagnosis Site'), ('session_rhythm', 'Session Rhythm')], max_length=50)),
                ('code', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'label'],
                'unique_together': {('category', 'code')},
            },
        ),
    ]
