# Generated by Django 6.0.3 on 2026-03-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_clinicclosedday_clinicclosurerange_holiday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoption',
            name='category',
            field=models.CharField(choices=[('gender', 'Gender'), ('dossier_type', 'Dossier Type'), ('marital_status', 'Marital Status'), ('social_security', 'Social Security'), ('session_rhythm', 'Session Rhythm'), ('session_status', 'Session Status')], max_length=50),
        ),
    ]
