# Generated by Django 6.0.3 on 2026-03-08 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_settings', '0003_alter_appoption_category'),
        ('clients', '0005_alter_treatment_completed_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(blank=True, limit_choices_to={'category': 'session_status', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_status', to='app_settings.appoption')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='clients.treatment')),
            ],
            options={
                'ordering': ['-session_date', '-created_at'],
            },
        ),
    ]
