# Generated by Django 6.0.3 on 2026-03-15 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0004_alter_appoption_category'),
        ('client_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='payment_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'payment_status', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_payment_status', to='app_settings.appoption'),
        ),
    ]
